[project]
name = "ch01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bellround", email = "rainarmy11@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "pymysql>=1.2.0",
]

[project.scripts]
ch01 = "ch01:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
